[package]
name = "libsvm_parser"
version = "0.2.1"
authors = ["MoonL1ght <ixav1@icloud.com>"]
edition = "2018"
keywords = ["libsvm", "parser"]
license = "MIT, APACHE"

[dev-dependencies]
pretty_assertions = "0.4.0"